---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: application.k8s.io/v1alpha1
    kind: Runtime
    metadata:
      name: fruit-backend-sb
      labels:
        application: my-app-1
    spec:
      deploymentMode: innerloop
      runtime: spring-boot
      exposeService: true
      envs:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "openshift-catalog"
  - apiVersion: application.k8s.io/v1alpha1
    kind: Link
    metadata:
      name: fruit-endpoint-sb
      labels:
        application: my-app-1
    spec:
      kind: Secret
      name: "Secret to be injected as EnvVar using Service's secret"
      targetComponentName: fruit-backend-sb
      ref: postgresql-db
  - apiVersion: application.k8s.io/v1alpha1
    kind: Service
    metadata:
      name: postgresql-db
      labels:
        application: my-app-1
    spec:
      name: postgresql-db
      class: dh-postgresql-apb
      plan: dev
      secretName: "postgresql-db"
      parameters:
        - name: "postgresql_user"
          value: "luke"
        - name: "postgresql_password"
          value: "secret"
        - name: "postgresql_database"
          value: "my_data"
        - name: "postgresql_version"
          value: "9.6"
