apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.application.k8s.io
spec:
  group: application.k8s.io
  version: v1alpha1
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - application
  scope: Namespaced