apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: runtimes.application.k8s.io
spec:
  group: application.k8s.io
  version: v1alpha1
  names:
    kind: Runtime
    listKind: RuntimeList
    plural: runtimes
    singular: runtime
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - application
  scope: Namespaced
  additionalPrinterColumns:
    - name: Type
      type: string
      JSONPath: .kind