apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: services.application.k8s.io
  labels:
    application: my-app-1
spec:
  group: application.k8s.io
  version: v1alpha1
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - application
  scope: Namespaced
  additionalPrinterColumns:
    - name: Type
      type: string
      JSONPath: .kind