apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: links.application.k8s.io
spec:
  group: application.k8s.io
  version: v1alpha1
  names:
    kind: Link
    listKind: LinkList
    plural: links
    singular: link
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - application
  scope: Namespaced
  additionalPrinterColumns:
    - name: Type
      type: string
      JSONPath: .kind