apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: component-operator
  template:
    metadata:
      labels:
        name: component-operator
    spec:
      serviceAccountName: component-operator
      containers:
        - name: component-operator
          image: quay.io/snowdrop/component-operator:0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - component-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: "my-spring-app"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "component-operator"
