apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  name: fruit-database
spec:
  services:
    - name: postgresql-db   # Name of the instance to be created within the namespace
      class: dh-postgresql-apb # Class or name of the service selected from the catalog
      plan: dev                # Plan selected : dev, ....
      parameters:
      - name: postgresql_user
        value: "luke"
      - name: postgresql_password
        value: "secret"
      - name: postgresql_database
        value: "my_data"
      - name: postgresql_version
        value: "9.6"