apiVersion: v1
kind: ImageStream
metadata:
  name: nodejs-rest-http
---

apiVersion: v1
kind: ImageStream
metadata:
  name: runtime
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'nodeshift/centos7-s2i-nodejs:10.x'
---

apiVersion: v1
kind: BuildConfig
metadata:
  name: nodejs-rest-http
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-rest-http:latest'
  source:
    binary:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'runtime:latest'
      incremental: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: 'true'
    project: nodejs-rest-http
    provider: nodeshift
    version: 2.0.1
  name: nodejs-rest-http
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    project: nodejs-rest-http
    provider: nodeshift
    app: nodejs-rest-http
---

apiVersion: v1
kind: DeploymentConfig
metadata:
  name: nodejs-rest-http
  labels:
    app: nodejs-rest-http
    provider: nodeshift
    project: nodejs-rest-http
    version: 2.0.1
spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /api/greeting
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /api/greeting
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
          image: nodejs-rest-http
          name: nodejs-rest-http
          securityContext:
            privileged: false
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
    metadata:
      labels:
        app: nodejs-rest-http
        project: nodejs-rest-http
        provider: nodeshift
        version: 2.0.1
  replicas: 1
  selector:
    app: nodejs-rest-http
    project: nodejs-rest-http
    provider: nodeshift
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nodejs-rest-http
        from:
          kind: ImageStreamTag
          name: 'nodejs-rest-http:latest'

---

apiVersion: v1
kind: Route
metadata:
  labels:
    project: nodejs-rest-http
    provider: nodeshift
    version: 2.0.1
  name: nodejs-rest-http
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nodejs-rest-http
